// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  content_type: dynamic(() => import("./ContentType")),
  education: dynamic(() => import("./Education")),
  hero3_d: dynamic(() => import("./Hero3D")),
  image_block: dynamic(() => import("./ImageBlock")),
  teach_list: dynamic(() => import("./TeachList")),
  text_blog: dynamic(() => import("./TextBock")),
};
